depend: [ShinyBase]
name: ShinyMail
main: com.hotmail.shinyclef.shinymail.ShinyMail
version: 1.1.3
commands:
   mail:
      description: Send mail to offline players and check/read your mail.
      usage: Invalid command. Type "/<command> help" for a list of commands.
   mailadmin:
      description: Admin tools such as reloading config.yml (where mail is stored) and checking people's mail.
      usage: Invalid command. Type "/<command> help for a list of admin commands.
      permission: ShinyMail.mailadmin
      permission-message: You don't have permission <permission>

permissions:
    ShinyMail.*:
        description: Gives access to all ShinyMail commands.
        children:
            ShinyMail.mailadmin: true
    ShinyMail.mailadmin:
        description: Allows you to access ShinyMail admin commands.
        default: op